site_name: Documentation
site_url: https://docs.daimahougames.com/
nav:
    - Core:
      - core/index.md
      - Features:
        - core/features/index.md
        - core/features/pawn.md
        - core/features/action-state.md
        - core/features/interaction.md
        - core/features/gestures.md
      - Visual Scripting:
        - core/visual/index.md
        - core/visual/instructions.md

    - Abilities: 
      - abilities/index.md
      - Installation: 
        - abilities/getting-started/index.md
      - Ability Asset:
        - abilities/ability-asset/index.md
        - Targeting System: abilities/ability-asset/targeting.md
        - Activation System: abilities/ability-asset/activation.md
        - Requirement System: abilities/ability-asset/requirements.md
        - Filter System: abilities/ability-asset/filters.md
        - Effect System: abilities/ability-asset/effects.md
      - Projectiles & Impacts:
        - abilities/projectiles/index.md
        - abilities/projectiles/projectiles.md
        - abilities/projectiles/impacts.md
      - Tutorials:
        - abilities/tutorials/index.md
      - Releases: releases.md

theme: 
  name: material
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.indexes

  palette: 
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate 
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/DaimahouGames
      name: Daimahou Games on Twitter
    - icon: fontawesome/solid/paper-plane
      link: mailto:<daimahou.studio@gmail.com>
      name: Contact us
  generator: false
  homepage: https://daimahougames.com

copyright: Copyright &copy; 2022 Nicolas Gerard

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
- stylesheets/extra.css