site_name: Documentation
site_url: https://docs.daimahougames.com/
nav:
    - Core:
      - core/index.md
    - Abilities: 
      - abilities/index.md

theme: 
  name: material
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
  palette: 
    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate 
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/DaimahouGames
      name: Daimahou Games on Twitter
    - icon: fontawesome/solid/paper-plane
      link: mailto:<daimahou.studio@gmail.com>
      name: Contact us

copyright: Copyright &copy; 2022 Nicolas Gerard

extra:
  generator: false