site_name: Documentation
site_url: https://docs.daimahougames.com/
plugins:
    - search
    # - with-pdf:
    #     author: Gerard Nicolas
    #     copyright: &copy 2022 DaimahouGames, Gerard Nicolas, All rights reserved.
    #     cover_title: Daimahou Gameplay Modules
    #     cover_subtitle: Documentation
nav:
    - Core:
      - index.md
      - Systems:
        - core/systems/index.md
        - Pawn:
          - core/systems/features/index.md
          - Features:
            - core/systems/features/brain.md
            # - core/systems/features/faction.md
          - States:
            - core/systems/states/default.md
            # - core/systems/states/move.md
        - Controller: core/systems/input/controller.md
        - core/systems/gestures.md
      - Game Creator Extensions: core/systems/extensions.md
      - Visual Scripting:
        # - core/visual/index.md
        - core/visual/instructions.md
        # - core/visual/conditions.md
      - Releases: core/releases.md

    - Abilities: 
      - abilities/index.md
      - Installation: 
        - abilities/getting-started/index.md
      - Ability Asset:
        - abilities/ability-asset/index.md
        - Targeting System: abilities/ability-asset/targeting.md
        - Activation System: abilities/ability-asset/activation.md
        - Requirement System: abilities/ability-asset/requirements.md
        - Filter System: abilities/ability-asset/filters.md
        - Effect System: abilities/ability-asset/effects.md
      - Pawn feautures:
        - abilities/features/caster.md
        - abilities/features/cooldown.md
      - Input: abilities/input.md
      - Projectiles & Impacts:
        - abilities/projectiles/index.md
      - Extras: abilities/extra.md
      - Tutorials:
        - abilities/tutorials/index.md
      - Releases: releases.md

#    - Grids:
#      - grids/index.md
#      - Releases: grids/releases.md
theme: 
  name: material
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.indexes

  palette: 
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate 
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/DaimahouGames
      name: Daimahou Games on Twitter
    - icon: fontawesome/solid/paper-plane
      link: mailto:<daimahou.studio@gmail.com>
      name: Contact us
  generator: false
  homepage: https://daimahougames.com

copyright: Copyright &copy; 2022 Nicolas Gerard, All rights reserved.

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_css:
- stylesheets/extra.css
